### ISSUE TITLE
same object ref doesn't work

### ISSUE THREAD

**Issue by sourcevault** [arthurlacoste/tampa#6]
input :
```yaml
global:
  proj: utils
  which: test
  file: test {{global.proj}}
```
ouput :
```
test {{global.proj}}
```
leaf can't reference truck.

**Comment by sourcevault** [comment]
A litle more debugging makes it seem you need to do two passes to make things work :


yaml file :

```yaml
global:
  proj: utils
  file: hello {{global.proj}}

vars:
  file: hello world

foo:
  - echo {{vars.file}}
```

json raw output:

```js
{                              
  "global": {                  
    "proj": "utils",           
    "which": "test1",          
    "file": "hello utils"      
  },                           
  "vars": {                    
    "file": "hello world"      
  },                           
  "foo": [                     
    "echo hello world"         
  ]                            
}                              
```

works correctly, but if you do this :

yaml file :

```yaml
global:
  proj: utils
  file: hello {{global.proj}}

vars:
  file: hello world

foo:
  - echo {{global.file}}
```

json raw output:

```js
{                                    
  "global": {                        
    "proj": "utils",                 
    "which": "test1",                
    "file": "hello utils"            
  },                                 
  "vars": {                          
    "file": "hello world"            
  },                                 
  "foo": [                           
    "echo hello {{global.proj}}"     
  ]                                  
}                                    
```

so it, seems `tampex` is unable to handle two levels of referencing.
